examples/spin.jl
The GR3.draw[sphere|cylinder|cone]mesh(...) functions require arrays of floats as parameters, even when there is only one value to pass, e.g. the radius of a single sphere. Passing individual floats lead to an error in Julia 0.5.
=> Fixed bugs in the spin example

src/GR.jl, test/runtests.jl
The use of `Pkg.dir` results in the standard path under .julia. If the package is installed elsewhere, such as in the preinstalled packages of JuliaBox (in /opt/julia_packages), the downloaded library is not found. Using `@__FILE__` solves that.
=> Enable use out of non-standard LOAD_PATH

deps/build.jl
Sorry for the delay, but to continue https://github.com/barche/QML.jl/issues/23#issuecomment-302429245 this uses QML to find out what Qt5 is used and adds it to the qt5plugin.so rpath. The advantage is that this works also when a non-homebrew Qt is used or a Qt from a non-Julia homebrew (my case) is used.
CC @scls19fr
=> Use rpath and QML-supplied path for Qt5

src/jlgr.jl
Easily testable with 
```julia
GR.histogram(rand(5000), nbins=10)
```
Before:
After:
=> Fixes the histogram bug where first and last bin are not filled properly

deps/build.jl
Base.JULIA_HOME has been deprecated and replaced with Sys.BINDIR. Pick
the right variable based on Julia version.
=> Use `Sys.BINDIR` on Julia > 0.7. (Fix for #117)

deps/build.jl
ElementaryOS needs to download "Ubuntu" binary of GR. This commit fixes the binary URL download in ElementaryOS.
=> Added ElementaryOS support

src/GR.jl
This seems a bit better than only checking whether the corresponding package was loaded or not.
What was the rationale for this change in the first place?
=> fix Atom and IJulia integration

src/jlgr.jl
Hi, thank you for your great work! I found this package when I was searching for a lightning fast plotting package for real-time image monitoring. GR works like a charm.
Today I came across an error, I would like to fix this. In short, `imshow()` function raises error with an flat image, `minimum(I) == maximum(I)`, because of zero-division in [plot_img(I)](https://github.com/jheinen/GR.jl/blob/366037d2cd7475def2f15065ba541eebffee0496/src/jlgr.jl#L740). For example, probably you can reproduce by doing this:
```julia
using GR
imshow(zeros(3, 3))
```
It raises Inexact Error.
I thought of three cases:
1. Normal image (`minimum(I) < maximum(I)`)
1. Flat image (`minimum(I) == maximum(I) > 0`)
1. Zero-filled image (`minimum(I) == maximum(I) == 0`)
The first one will be plotted as same as before. …
=> Fix bug in normalization

src/GR.jl
I have a module that exports a struct `Atom` to represent actual atoms.  This PR checks to ensure that `Main.Atom` actually is a module, and not an atom, before assuming it's an editor. :smile: 
Also added a similar check for `IJulia` on the line above.
=> Check that `Main.Atom` and `Main.IJulia` are modules

src/GR.jl, src/jlgr.jl
There were 2 issues, broadcasting instead of function and some `Function` type comparisons causing false
branching because every function has its own type and `Function` being their `supertype`.
=> Fix #213 Callable Syntax & Function checks

src/jlgr.jl
This pull-request implements a new option "clim" for (`scatter`, `heatmap`, `scatter3`, `imshow`) to control the color scaling of those plots.
This functionality is an equivalent of Matlab's [`imagesc(__, clims)`](https://mathworks.com/help/matlab/ref/imagesc.html) or matplotlib's [`vmin` and `vmax` options](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.imshow.html).
As for the name `clim`, since GR.jl already had options named (`xlim`, `ylim`, `zlim`), I just followed it. However, I have no strong opinion about it, please let me know if you prefer other names. For example, vmin and vmax.
An example of concrete usage is to avoid unwanted normalization by hot pixels in an image.
```julia
img = rand(Float64, 100, 100);
img[50, 50] = 10.0
imshow(img)
imshow(img, clim=(0, 1))
```
=> Introduce an option to scale colors of a plot

src/GR.jl, src/jlgr.jl
Functions to disable/enable the plotting of grid lines, and to customize the intervals of minor and major ticks (limited to plots of Euclidean axes, i.e. x, y, z).
Answers part of #218 (except setting the ratio of the plot).
=> Customize axes

src/GR.jl, src/jlgr.jl
This allows to use a more "matlab-like" work flow, such that you can first plot the data, and then set the plot title, legend, axes labels, limits, etc. (now you must normally do it the other way round).
The plot still has to be manually redrawn, by calling the proposed function `redraw` (feel free to rename it if the name is not good).
`create_context` has new methods to allow create a context without telling explicitly the kind (just take the one that already exists).
The attributes that can be passed as keyword arguments to `redraw` are not fixed in the figure (they are not reminded if `redraw` is called later on; they are just saved in the global `ctx`). But that's consistent with the current logic, I think.
=> add methods to `create_context` and define `redraw`

src/jlgr.jl
Minor modification of #226, such that when tick axes are customized, by default the major ticks intervals are equal to the minor tick intervals.
=> Default custom tick intervals

src/jlgr.jl
Add functions `hasline` and `hasmarker` in `jlgr` for clearer interpretation of the output of `GR.uselinespec`.
The older code equivalent to `hasline(mask)` was `mask in (0, 1, 3, 4, 5)`, which neglected line specs that combined line, marker and color specs (e.g. "-or") -- in that case `mask` was `0b111`, i.e. `7`. In those cases, only the marker (not the line) was plotted.
=> fix line specifications

src/GR.jl, src/jlgr.jl
New `axeslbl` function in `GR`;  `xticklabels` and `yticklabels` in `jlgr`.
For instance:
```julia
xticks(π/8,4)
xticklabels((x)->Base.Printf.@sprintf("%0.1f\\pi",x/π))
plot(-2π:0.01:2π, sin.(-2π:0.01:2π))
```
`xticklabels`, `yticklabels` also accept a sequence of strings to associate them to integer values (1, 2, 3...). It may come in handy for future functionalities, like bar plots.
=> Custom tick labels

src/GR.jl
This solves a situation like the following one:
``` julia
using GR
GR.inline("mov")
for x = 0:90
plot((0:360) .+ x, sind)
end
GR.inline()
plot((0:360), sind)
```
This works nicely in Atom or in a Jupyter notebook, because `GR.inline()` by default sets the global `mime_type` to `"svg"`, which is what those environments use to show plots.
But in the REPL the default `mime_type` is `GR.None` (i.e. `Union{}`). So `GR.inline()` does close the video file (this is fine), but does not get back to the default context.
I thought on two possible workarounds:
1. Modify `GR.inline` such that the default MIME type is not always `"svg"`, but depends on the environment.
2. Add a function that resets `mime_type` to `GR.None`, which is the general default, as in the REPL. (Thus, in the previous example you …
=> add offline

src/jlgr.jl
In this example:
```julia
angles = LinRange(0, 2pi, 40)
radii = LinRange(0, 2, 40)
polar(angles, radii)
```
In master the angle labels are clockwise, although the plotted angles are counter-clockwise:
This PR draws the correct labels:
=> fix draw_polar_axes

src/gr3.jl
Hi. Thank you for the great work. 
This pull-request change Int32 -> UInt32 in `createisosurfacemesh`
```C
GR3API int gr3_createisosurfacemesh(int *mesh, GR3_MC_DTYPE *data, GR3_MC_DTYPE isolevel, unsigned int dim_x,
unsigned int dim_y, unsigned int dim_z, unsigned int stride_x,
unsigned int stride_y, unsigned int stride_z, double step_x, double step_y,
double step_z, double offset_x, double offset_y, double offset_z)
```
https://github.com/sciapp/gr/blob/9d96e8e0d8210b819822047f3011e528e191e7d4/lib/gr3/gr3_convenience.c#L861-L864
=> Fixed `createisosurfacemesh`

src/GR.jl
If `mime_type` is "mov", "mp4" or "webm", the HTML generated by `GR.show` tagged the video object as "video/mp4" in all cases.
This leaves that tag only if `mime_type` is "mp4". For "webm" it changes to "video/webm", and for "mov" to "video/quicktime".
=> Tag videos with the correct mime types

src/GR.jl
I found a small typo.
`gr_copyseg` is not function but struct (and this is not exported).
=> modified gr_copyseg to gr_copysegws

README.md
The correct URL is `generated/gr`, not `examples/gr`.
=> Fix Link to Plots examples in README

src/GR.jl
Some int functions were implemented as void functions.
I modified.
ex) [gr_setspace in gr.h](https://github.com/sciapp/gr/blob/master/lib/gr/gr.h#L92) and [gr_setspace in GR.jl](https://github.com/jheinen/GR.jl/blob/master/src/GR.jl#L1919-L1923)
=> modified some int function to return int value

src/GR.jl
From the next release onward, the VSCode extension will have a switch to disable the internal plot pane, just like Juno, so GR should respect that.
=> improve VSCode/Atom integration

src/GR.jl
This fixes errors with the new JLL, as seen in https://github.com/jheinen/GR.jl/issues/314#issuecomment-739054665
=> Dereference GR_jll.LIBPATH as required in new JLL

deps/build.jl, src/GR.jl
This is a lighter version of #386 that does not use Refs and should be more compatible with Julia 1.5.
The basic idea is that `touch(pathof(GR))` is needed in order to force GR.jl to recompile in the next Julia session.
Unlike #386 this requires the user to restart Julia.
=> Use constants, but do `touch(pathof(GR))`

.travis.yml, Project.toml, deps/build.jl, src/GR.jl, src/gr3.jl
This version uses `Libdl.dlsym` to load function pointers from library handles set in `__init__`. If `GR_jll` is loaded, then this will use the handles that it loaded.
The library handles are constant references to a `Ptr{Nothing}`. This version should work in Julia 1.5 and Julia 1.6.
An added benefit is that GR can be immediately used after rebuilding. The Julia session does not need to be restarted.
By the third cold execution of GR, things should be relatively fast.
```julia
$ julia
_
_       _ _(_)_     |  Documentation: https://docs.julialang.org
(_)     | (_) (_)    |
_ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
| | | | | | |/ _` |  |
| | |_| | | | (_| |  |  Version 1.5.1 (2020-08-25)
_/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/ …
```
=> Using Libdl.dlsym to dynamically load function pointers

src/js.jl
This ensures that GR.init() has been called upon `init_pluto`. This should help address potential world age issues In Pluto.
=> init_pluto calls GR.init()

src/GR.jl
Windows OS permits usernames with spaces. So, when building GR using the default BinaryBuilder option, `gksqt.exe` will fail to start when its path contains the username with spaces. This will fail to plot in the Julia REPL producing the output shown below.
To fix the problem, this pull request simply surrounds the full path to `gksqt.exe` with quotes for Windows OS.
**Before the fix:**
```               _
_       _ _(_)_     |  Documentation: https://docs.julialang.org
(_)     | (_) (_)    |
_ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
| | | | | | |/ _` |  |
| | |_| | | | (_| |  |  Version 1.6.0 (2021-03-24)
_/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |
julia> versioninfo()
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 …
```
=> Fix GR plot when using BinaryBuilder option in Windows due to spaces in the path to gksqt.exe

src/GR.jl, src/funcptrs.jl
This fixes the issue discussed in https://github.com/jheinen/GR.jl/commit/e2f97d2a9a7086a5913a821615b81c3c4e8e24d7
The primary fix is to pass `always` through `load_libs` back to `init` rather than always calling `init(true)` from `load_libs`.
This allows `check_env[]` to be set to `false` so that environmental variables are not reset upon trying to plot.
Before the fix, but with the the debug statements, I see that plotting attempts to change `GKS_FILEPATH`. You can simulate this by changing Line 419 to `load_libs(true)` rather than `load_lib(always)`.
```julia
juila> ENV["JULIA_DEBUG"] = "GR"
julia> using GR; inline("mov")
┌ Debug: GR Binaries:
│   GR.gr_provider[] = BinaryBuilder
│   GR.libGR = libGR.dll
│   GR.libGR3 = libGR3.dll
│   GR.libGRM = libGRM.dll
└ @ GR …
```
=> Fix Jupyter notebooks, add debug statements and inline documentation

deps/build.jl, src/jlgr.jl
I noticed many pre-1.0isms in the code base and went about cleaning them up. This improves inference in many cases and reduces garbage collection pressure. Some example timing with the test suite:
This PR:
```
steve:~/.julia/dev/GR (sjk/inf1=)$ julia --project=. test/runtests.jl
16.599929 seconds (41.29 M allocations: 2.340 GiB, 5.26% gc time, 5.96% compilation time)
```
Master:
```
steve:~/.julia/dev/GR (sjk/inf1=)$ julia --project=. test/runtests.jl
21.406740 seconds (43.16 M allocations: 2.478 GiB, 4.38% gc time, 4.37% compilation time)
```
=> Grab bag of inference improvements

src/jlgr.jl
This reduces some of the allocations and improves the efficiency of the `colormap` call used in the `heatmap` function.
=> reduce allocation and improve efficiency of heatmap

src/funcptrs.jl
This [convention](https://docs.julialang.org/en/v1/stdlib/Logging/#:~:text=using%20the%20tuple-,exception%3D(ex%2Cbt).,-Examples) will make sure that the error is displayed nicely in the REPL and other IDEs. *Feel free to merge/close/edit without discussion!*
=> Tweak log "Error importing GR_jll"

src/jlgr.jl, test/runtests.jl
This avoid some union splitting in Symbol comparions by omitting the use of `in` and cleans up global `plt[]` references.
Time to run test suite:
before:
```
17.279085 seconds (26.02 M allocations: 1.404 GiB, 4.46% gc time, 86.64% compilation time)
elapsed time (ns): 17279085303
gc time (ns):      770870444
bytes allocated:   1507284631
pool allocs:       26015226
non-pool GC allocs:8463
malloc() calls:    154
realloc() calls:   17
GC pauses:         32
full collections:  2
```
after:
```
14.921943 seconds (24.91 M allocations: 1.350 GiB, 4.77% gc time, 84.44% compilation time)
elapsed time (ns): 14921942825
gc time (ns):      711853081
bytes allocated:   1449184611
pool allocs:       24903415
non-pool GC allocs:7990
malloc() calls:    124
realloc() calls:   12
GC pauses:         32
full …
```
=> Misc compilation and memory optimizations

src/GR.jl, src/funcptrs.jl, test/runtests.jl
- ~~clamp `PATH` on `windows` (https://github.com/JuliaPlots/Plots.jl/issues/4375#issuecomment-1263336062)~~;
- set `GKS_QT` on windows, with `PATH` changed for `dll`s loading (this seems to have disappeared).
Try to fix https://github.com/jheinen/GR.jl/issues/475.
There was already a similar test in https://github.com/jheinen/GR.jl/blob/ce153a2626413668d0387d6ff62008e2dc3fbf55/test/runtests.jl#L37, so I don't really know what is going on (probably a low level library issue).
I won't be available until tomorrow. @jheinen, you can push in this branch if needed.
=> `windows` workarounds

src/GR.jl
Fix https://github.com/jheinen/GR.jl/issues/475.
@BioTurboNick, if you could confirm, thanks a lot.
I really don't know how to write a test for this, so it does not reproduce ...
We really need low-level `gr` debugging tools (https://github.com/JuliaPlots/Plots.jl/issues/4375#issuecomment-1263573163).
=> `windows` `gks_qt` fix

src/GR.jl, src/funcptrs.jl, src/preferences.jl
Try to fix https://github.com/jheinen/GR.jl/issues/478.
AFAIK there is no `rpath` mechanism on `windows` so we still have to set `PATH`.
`DYLD_FALLBACK_LIBRARY_PATH` on `macOS` seems safe since it does not preempt the library search path as `LD_LIBRARY_PATH` does on `linux` (which is pure evil, only intended to debug stuff, and **should never be used in published software**).
Maybe we should enforce `rpath` compiler flags explicitly in [build_tarballs.jl](https://github.com/JuliaPackaging/Yggdrasil/blob/master/G/GR/build_tarballs.jl) ?
They seem to be set under the hood by `CMake`.
Also modernize `OS` detection (simplifications).
=> remove `LD_LIBRARY_PATH` on `linux`, should be handled by `rpath`

.github/workflows/ci.yml, test/downstream_test.jl
This is a proposal in order to avoid potential `GR` induced `Plots` regressions.
`Plots` and `GR` are tightly linked since `GR` is the default `Plots` backend.
As a result, releasing `GR` changes without testing `Plots` could potentially break `Plots`.
I'm taking the latest example of https://github.com/JuliaPlots/Plots.jl/pull/4507, where `GR@0.70.0` passed `Plots` `ci` whereas `GR@0.70.1` (a patch version, hence declared as non-breaking) broke `Plots` on `windows`, for all `julia` versions, at the precompilation stage.
By testing `Plots` **before** a commit or a PR lands in `GR.jl`, we ensure that potential regressions are caught here, and don't land in `Plots` by inadvertence (since we usually don't pin the `GR` patch version there).
It is worth mentioning that we also run downstream …
=> add downstream `Plots` tests

.github/workflows/ci.yml, README.md, src/funcptrs.jl, test/downstream_test.jl
This does not use `SetDefaultDllDirectories` and also does not set the `PATH`.
It mainly relies upon the `GRDIR` environment variable to aid in library path loading.
=> Do not use SetDefaultDllDirectories

src/preferences.jl
No need to do the search a second time; we can re-use the cached value that was already calculated at the JLL's `__init__()` time.
=> Use `GR_jll.artifact_dir` instead of `find_artifact_dir()`

src/preferences.jl
`GR_jll` is used in `__init__` and thus is not optional.
Rethrow the error after suggesting possible fixes.
TODO: Review fixing advice
=> Error on GR_jll failure

Project.toml, src/downloader.jl, src/preferences.jl
Follow up to a conversation on Slack in the `#ttfx` channel. 
In version 1.11, depending on Pkg.jl will no longer be free because it's not in the sysimage, this makes GR.jl slower to load on v1.11 than v1.10. 
The code in GR.jl that uses Pkg is non-functional, since doing a `@eval using QML` when QML.jl isn't in the dep-list will just cause an error. This has probably been failing the entire time this code existed, but wasn't noticed because it's wrapped in a `try/catch` block without even a `@debug` statement. 
This PR alone is not enough to fix the ttfx regression for GR in v1.11, since some of the binary artifacts like the `Xorg` stack also are loading Pkg, but those are apparently being dealt with as well.
=> Excise `Pkg` and `UUIDs`

.github/workflows/ci.yml
One should run non-regression tests:
- on the lowest declared julia version in `Project.toml`;
- on the current julia lts version;
- on the current julia `1` release branch.
Please run CI in the [GR.jl](https://github.com/jheinen/GR.jl) repo when releasing a new [gr](https://github.com/sciapp/gr) version in order to avoid [breaking](https://github.com/JuliaPlots/Plots.jl/issues/5041) [Plots.jl](https://github.com/JuliaPlots/Plots.jl), this isn't difficult.
=> use `lts` keyword for CI

examples/gtk_ex.jl
See: https://docs.gtk.org/gtk3/method.Widget.set_double_buffered.html
=> double_buffered is deprecated and breaks on Windows
